name: Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:

  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
          - os: macos
            NAME: macos
            BINARY_PATH: |
              build/macos/Build/Products/Release/
              !build/macos/Build/Products/Release/*
              build/macos/Build/Products/Release/bma_desktop_setup.app/

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Cache libs
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache

      - name: Get Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install Linux Depenencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev

      - name: Enable Desktop
        run: flutter config --enable-${{matrix.NAME}}-desktop

      - name: Get Libs
        run: flutter pub get

      - name: Build Release
        run: flutter build ${{matrix.NAME}} --release

      - name: Upload Release Files
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.NAME}}-build
          path: ${{matrix.BINARY_PATH}}
