name: Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Cache libs
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache

      - name: Get Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Get Libs
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test

  build:
    needs: test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
        include:
          - os: macos
            NAME: macos
            BINARY_PATH: build/macos/Build/Products/Release/setup4bmatotp.app/

          - os: ubuntu
            NAME: linux
            BINARY_PATH: build/linux/x64/release/bundle/

          - os: windows
            NAME: windows
            BINARY_PATH: build/windows/runner/release/

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Cache libs
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache

      - name: Get Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install Linux Depenencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev

      - name: Enable Desktop
        run: flutter config --enable-${{matrix.NAME}}-desktop

      - name: Get Libs
        run: flutter pub get

      - name: Build Release
        run: flutter build ${{matrix.NAME}} --release

      - name: Upload Release Files
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.NAME}}-build
          path: ${{matrix.BINARY_PATH}}
